import google.generativeai as genai
import os
from dotenv import load_dotenv
import logging

# Load environment variables
load_dotenv()

logger = logging.getLogger(__name__)

class GeminiClient:
    def __init__(self):
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")
        
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-1.5-flash')
        
    async def generate_summary(self, text_content: str) -> str:
        """Generate summary using Gemini AI."""
        try:
            prompt = self._create_summary_prompt(text_content)
            
            logger.info("Sending request to Gemini AI")
            response = self.model.generate_content(prompt)
            
            if not response.text:
                raise Exception("No summary generated by Gemini AI")
            
            logger.info("Summary generated successfully")
            return response.text
            
        except Exception as e:
            logger.error(f"Error generating summary: {e}")
            raise Exception(f"Failed to generate summary: {e}")
    
    def _create_summary_prompt(self, text_content: str) -> str:
        """Create an optimized prompt for PDF summarization."""
        prompt = f"""
        You are an expert document summarizer. Please analyze the following PDF content and create a comprehensive, well-structured summary.

        Instructions:
        1. Create a clear, concise summary that captures the main points and key information
        2. Organize the summary with appropriate headings and sections
        3. Highlight important facts, figures, and conclusions
        4. Maintain the logical flow and structure of the original document
        5. Use bullet points where appropriate for better readability
        6. Aim for a summary that is about 20-30% of the original length
        7. Focus on actionable insights and key takeaways

        PDF Content:
        {text_content}

        Please provide a well-formatted summary:
        """
        return prompt